version: "3.8"
services:
  mycelium_app:
    container_name: mycelium_app
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    depends_on:
      - mycelium_db
    networks:
      - app_network

  mycelium_nginx:
    container_name: mycelium_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - mycelium_app
    environment:
      NGINX_FPM_HOST: mycelium_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  mycelium_db:
    container_name: mycelium_db
    image: mysql:8.0.20
    restart: always
    volumes:
      - ./storage/db-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mycelium
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app_network

  mycelium_redis:
    container_name: mycelium_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge